# Generated by Django 2.1.1 on 2018-10-09 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textconvertor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageviewer',
            name='name',
        ),
    ]
